# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Development'

steps:
- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'Building $(buildConfiguration)'
- task: DotNetCoreCLI@2
  displayName: 'Testing $(buildConfiguration)'
  inputs:
    command: 'test'
    projects: '**/*Tests/*.csproj'
    arguments: '--configuration $(buildConfiguration)'
- task: DotNetCoreCLI@2
  displayName: 'Publishing $(buildConfiguration)'
  inputs:
    command: publish
    publishWebProjects: true
    arguments: '--configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)'
    zipAfterPublish: true
- task: PublishBuildArtifacts@1
  displayName: 'Storing Build Artifact'
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'ThAmCo.Products'
- task: AzureWebApp@1
  displayName: 'Deploying $(buildConfiguration) to test environment'
  inputs:
    azureSubscription: 'Azure for Students(d62a7fea-d138-4af2-a583-36271db165bf)'
    appName: 'ThAmCoProducts'
    appType: webAppLinux
    package: $(System.ArtifactsDirectory)/**/*.zip